name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/ai-integration
  pull_request:
    branches:
      - main
      - feature/ai-integration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node dependencies
        run: npm install

      - name: Run tests (placeholder)
        run: echo "No tests yet. This is a placeholder."

      - name: Lint code (placeholder)
        run: echo "No linter configured. This is a placeholder."

      - name: IA Workflow Status
        run: echo "✅ Le pipeline IA est prêt. Les IA collaboreront manuellement via Copilot et ChatGPT."
      
      - name: Run AI Function with OpenAI (Node.js)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          node ai/agentIA.js
